### ISSUE TITLE
A problem when i use the output in CMAQv5.4

### ISSUE THREAD

**Issue by Starrry22** [barronh/finn2cmaq#5]
Hi, I encountered a problem when I added the output to CMAQv5.4 with the cb6r3_ae7_aq mechanism. Here is my log file. [CTM_LOG_001.v54_intel_tibet27km_20220727.txt](https://github.com/user-attachments/files/17361172/CTM_LOG_001.v54_intel_tibet27km_20220727.txt). I searched the problem and found this [https://forum.cmascenter.org/t/could-not-extract-gr-emis-001-file-in-cmaq-run/1497](url). It seems like there are some species missed in the output but I don't know how to map these species or where to find the mapping profile. Could you give me some advice, please.

**Comment by barronh** [comment]
See discussion at https://forum.cmascenter.org/t/could-not-extract-finn-emission-file-in-cmaqv5-4/5285

**Comment by Starrry22** [comment]
> See discussion at https://forum.cmascenter.org/t/could-not-extract-finn-emission-file-in-cmaqv5-4/5285

Thank you for your reply.
